CON-2784 CoP banner displayed on CoE record
SkillsFundingAgency/das-employercommitments pull request #282
Opened 2020-12-01 14:54 UTC by ben1stone

2020-12-02 08:45 UTC, hkf-tech requested changes

2020-12-02 08:45 UTC, hkf-tech commented on src/SFA.DAS.EAS.Web/Views/EmployerManageApprentices/Details.cshtml
> +                @if (Model.Data.HasApprovedChangeOfProviderRequest && Model.Data.IsEmployerContinuation)
line 88, should that be IsEmployerContinuation

2020-12-02 08:45 UTC, hkf-tech commented on src/SFA.DAS.EAS.Web/Views/EmployerManageApprentices/Details.cshtml
> +                @if (Model.Data.HasApprovedChangeOfProviderRequest && Model.Data.IsEmployerContinuation)
something, i just noticed all the if condition have the same text - we can remove the nested if else, as one of them is going to be true.

2020-12-02 14:16 UTC, cofaulco approved these changes

2020-12-04 11:07 UTC, hkf-tech approved these changes

2020-12-04 11:08 UTC, merged